site_name: pygraphics
site_url: https://pygraphics.readthedocs.io
repo_url: https://github.com/PyDevices/pygraphics/
edit_uri: edit/main/docs/
copyright: "Copyright 2024, Brad Barnett"
docs_dir: docs
site_dir: site

theme:
  name: material
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.top
    - search.suggest
    - content.code.copy

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - gen-files:
      scripts:
        - scripts/mkdocs_gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          paths: [lib]
          options:
            show_source: false
            show_root_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            docstring_style: google
            merge_init_into_class: true
            filters:
              - "!^_"
